# Generated by Django 5.2.9 on 2026-01-02 20:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=128)),
                (
                    'measurement_unit',
                    models.CharField(
                        choices=[
                            ('граммы', 'г'),
                            ('милилитры', 'мл'),
                            ('штуки', 'шт.'),
                            ('столовые ложки', 'ст.л.'),
                            ('чайные ложки', 'ч.л.'),
                        ],
                        max_length=64,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
                'indexes': [
                    models.Index(
                        django.db.models.functions.text.Lower('name'),
                        name='ingredient_name_idx',
                    )
                ],
            },
        ),
    ]
