# Generated by Django 5.2.9 on 2026-01-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(
                choices=[
                    ('граммы', 'г'),
                    ('милилитры', 'мл'),
                    ('штуки', 'шт.'),
                    ('столовые ложки', 'ст.л.'),
                    ('чайные ложки', 'ч.л.'),
                ],
                max_length=64,
                verbose_name='Единица измерения',
            ),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
