version: 2

updates:
  # =========================
  # Frontend — React (npm)
  # =========================
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    target-branch: "dev"
    versioning-strategy: "increase"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
    ignore:
      # Не открывать PRы для мажорных обновлений (всех пакетов)
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # =========================
  # Backend — Python (pip)
  # requirements.txt
  # =========================
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    target-branch: "dev"
    versioning-strategy: "increase"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # =========================
  # GitHub Actions (CI)
  # =========================
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/CI"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "CI"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows/CD"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "CD"
