#!/usr/bin/env python3
"""
Export Django models to DBML for dbdiagram.io.

Usage:
  # from project root
  - `python scripts/export_dbml.py  # all non-django contrib apps`
  - `python scripts/export_dbml.py --apps users recipes ingredients`
  - `DJANGO_SETTINGS_MODULE=your_project.settings python scripts/export_dbml.py`
"""

import argparse
import os
import sys

import django
from django.apps import apps
from django.db.models import ForeignKey, ManyToManyField, OneToOneField


# ---- Config / args ----
parser = argparse.ArgumentParser(
    description='Export Django models to DBML for dbdiagram.io'
)
parser.add_argument(
    '--apps',
    nargs='*',
    help='List of app labels to include (default: auto user apps)',
)
parser.add_argument(
    '--exclude', nargs='*', help='App labels to exclude', default=[]
)
parser.add_argument(
    '--no-header', action='store_true', help='Do not print header comment'
)
args = parser.parse_args()

# если запуск не из директории с manage.py,
# убедитесь, что установлена переменная DJANGO_SETTINGS_MODULE
script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.abspath(os.path.join(script_dir, '..'))

# Гарантируем, что корень проекта в sys.path
#  тогда импорт foodgram.settings найдётся.
if project_root not in sys.path:
    sys.path.insert(0, project_root)

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'foodgram.settings')
try:
    django.setup()
except Exception as e:
    print('Ошибка при инициализации Django:', e, file=sys.stderr)
    print(
        'Убедитесь, что DJANGO_SETTINGS_MODULE задан '
        'и виртуальное окружение активировано.',
        file=sys.stderr,
    )
    sys.exit(2)

# ---- Helpers ----
FIELD_TYPE_MAP = {
    'AutoField': 'int',
    'BigAutoField': 'bigint',
    'IntegerField': 'int',
    'BigIntegerField': 'bigint',
    'SmallIntegerField': 'smallint',
    'FloatField': 'float',
    'DecimalField': 'decimal',
    'CharField': 'varchar',
    'TextField': 'text',
    'BooleanField': 'boolean',
    'NullBooleanField': 'boolean',
    'DateField': 'date',
    'DateTimeField': 'timestamp',
    'TimeField': 'time',
    'UUIDField': 'uuid',
    'JSONField': 'json',
    'ForeignKey': 'int',
    'OneToOneField': 'int',
    # fallback will be 'text'
}


def map_field_type(f):
    t = type(f).__name__
    return FIELD_TYPE_MAP.get(t, f.get_internal_type() or 'text')


def safe_name(name: str) -> str:
    """
    Преобразует произвольную строку в безопасное имя для DBML:
    - нормализует Unicode и транслитерует в ASCII (удаляет диакритику);
    - заменяет любые пробельные последовательности на один underscore;
    - заменяет все символы, кроме A-Z, a-z, 0-9 и _, на underscore;
    - сводит несколько underscore в один;
    - если имя начинается с цифры — добавляет префикс `t_`;
    - если в результате пусто — возвращает 'unnamed'.
    """
    import re
    import unicodedata

    if name is None:
        return 'unnamed'

    s = str(name).strip()
    s = re.sub(r'\s+', '_', s)

    # Unicode нормализация + попытка транслитерации в ASCII
    s = unicodedata.normalize('NFKD', s)
    s = s.encode('ascii', 'ignore').decode('ascii')

    # заменить все неразрешённые символы на underscore
    s = re.sub(r'[^0-9A-Za-z_]', '_', s)

    # свернуть подряд идущие underscore в один
    s = re.sub(r'_+', '_', s)

    # убрать ведущие/концевые underscore после свёртки
    s = s.strip('_')

    # если начинается с цифры — добавить префикс
    if re.match(r'^\d', s):
        s = f't_{s}'

    if not s:
        return 'unnamed'

    return s


# выбор apps
if args.apps:
    app_labels = args.apps
else:
    # по умолчанию: включить installed apps, кроме django contrib
    app_labels = [
        a.label
        for a in apps.get_app_configs()
        if not a.name.startswith('django.')
        and a.label not in (args.exclude or [])
    ]

# список моделей
models = []
for label in app_labels:
    try:
        cfg = apps.get_app_config(label)
    except LookupError:
        print(f"Warning: app '{label}' not found, skipping.", file=sys.stderr)
        continue
    for m in cfg.get_models():
        models.append(m)

# учесть уже записанные таблицы (db_table names)
written_tables = set()
lines = []

if not args.no_header:
    lines.append('// Generated by scripts/export_dbml.py')
    lines.append('// Paste into https://dbdiagram.io and Run')
    lines.append('')

# инициализация таблиц
for model in models:
    tbl = model._meta.db_table
    if tbl in written_tables:
        continue
    written_tables.add(tbl)
    lines.append(f'Table {safe_name(tbl)} {{')
    # поля: model._meta.local_fields (только конкретные поля, исключая m2m)
    for f in model._meta.local_fields:
        # name, type, pk, null, unique
        name = f.column or f.name
        dtype = map_field_type(f)
        attrs = []
        if getattr(f, 'primary_key', False):
            attrs.append('pk')
        if not getattr(f, 'null', False) and not getattr(
            f, 'primary_key', False
        ):
            attrs.append('not null')
        if getattr(f, 'unique', False):
            attrs.append('unique')
        # пропускаем значения по умолчанию, чтобы избежать беспорядка
        attrs_s = f' [{", ".join(attrs)}]' if attrs else ''
        lines.append(f'  {safe_name(name)} {dtype}{attrs_s}')
    lines.append('}')
    lines.append('')

# сбор отношений (FKs/OneToOne)
refs = []
# Для неявных таблиц M2M мы создадим синтетические записи и ссылки в таблицах.
m2m_auto_tables = {}

for model in models:
    src_tbl = model._meta.db_table
    for f in model._meta.get_fields():
        # ForeignKey / OneToOne -> add Ref
        if isinstance(f, (ForeignKey, OneToOneField)):
            tgt = f.related_model._meta.db_table
            src_col = f.column
            tgt_pk = f.related_model._meta.pk.column
            refs.append(
                f'Ref: {safe_name(src_tbl)}.{safe_name(src_col)} > {safe_name(tgt)}.{safe_name(tgt_pk)}'
            )
        elif isinstance(f, ManyToManyField):
            # обработка many-to-many
            through = f.remote_field.through
            # if through is auto-created by Django, include an auto table
            if getattr(through._meta, 'auto_created', False):
                jt_name = through._meta.db_table
                if (
                    jt_name not in written_tables
                    and jt_name not in m2m_auto_tables
                ):
                    # создать простую join-таблицу с 2 fk столбцами
                    a_tbl = model._meta.db_table
                    b_tbl = f.related_model._meta.db_table
                    a_pk = model._meta.pk.column
                    b_pk = f.related_model._meta.pk.column
                    col_a = f'{model._meta.model_name}_id'
                    col_b = f'{f.related_model._meta.model_name}_id'
                    m2m_auto_tables[jt_name] = (
                        a_tbl,
                        b_tbl,
                        col_a,
                        col_b,
                        a_pk,
                        b_pk,
                    )
            else:
                # явная through-модель — это одна из моделей в списке, и она будет напечатана отдельно.
                pass

# печать auto m2m таблиц
for jt, data in m2m_auto_tables.items():
    a_tbl, b_tbl, col_a, col_b, a_pk, b_pk = data
    if jt in written_tables:
        continue
    written_tables.add(jt)
    lines.append(f'Table {safe_name(jt)} {{')
    lines.append(
        f'  {safe_name(col_a)} int [ref: > {safe_name(a_tbl)}.{safe_name(a_pk)}]'
    )
    lines.append(
        f'  {safe_name(col_b)} int [ref: > {safe_name(b_tbl)}.{safe_name(b_pk)}]'
    )
    lines.append('}')
    lines.append('')
    refs.append(
        f'Ref: {safe_name(jt)}.{safe_name(col_a)} > {safe_name(a_tbl)}.{safe_name(a_pk)}'
    )
    refs.append(
        f'Ref: {safe_name(jt)}.{safe_name(col_b)} > {safe_name(b_tbl)}.{safe_name(b_pk)}'
    )

# добавляем собранные отношения
if refs:
    lines.append('// Relationships')
    for r in refs:
        lines.append(r)

# вывод
print('\n'.join(lines))
