# Generated by Django 5.2.9 on 2026-01-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(
                max_length=32, unique=True, verbose_name='Название'
            ),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(
                max_length=32, unique=True, verbose_name='Слаг'
            ),
        ),
    ]
