# Generated by Django 5.2.9 on 2026-01-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ingredients', '0002_alter_ingredient_measurement_unit_and_more'),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(
                through='recipes.RecipeIngredient', to='ingredients.ingredient'
            ),
        ),
    ]
