# Generated by Django 5.2.9 on 2026-01-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('ingredients', '0002_alter_ingredient_measurement_unit_and_more'),
        ('recipes', '0003_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(
                related_name='recipes',
                through='recipes.RecipeIngredient',
                to='ingredients.ingredient',
                verbose_name='Ингредиенты',
            ),
        ),
    ]
