# Generated by Django 5.2.9 on 2026-01-12 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.AlterModelOptions(
            name='shoppingcartitem',
            options={
                'verbose_name': 'Объект в корзине',
                'verbose_name_plural': 'Объекты в корзине',
            },
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
