name: Telegram notification
on:
  push:
    branches:
      - dev

jobs:
  send_message:
    name: Send Telegram message
    runs-on: ubuntu-latest
    steps:
    - name: Send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Деплой *Foodgram* успешно выполнен!
          Автор коммита - ${{ github.actor }}
          Сообщение коммита - ${{ github.event.commits[0].message }}
          Ссылка на коммит - https://github.com/${{github.repository}}/commit/${{github.sha}}
